### ISSUE TITLE
Node 'self' example does not validate.

### ISSUE THREAD

**Issue by sparkpunkd** [AMWA-TV/nmos-discovery-registration#38] opened 2018-02-16 18:14 UTC
When testing a JSON validator for v1.2 schema, the [nodeapi self example](/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/examples/nodeapi-v1.1-self-get-200.json) does not validate against [node.json](/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/APIs/schemas/node.json).

The `interfaces.port_id` property has regex `^([0-9a-f]{2}[-]){5}([0-9a-f]{2})$` but the example value is `74:26:96:db:87:32`. 

I also note that the `interfaces.chassis_id` is validating against the `^.+$` rule and not the MAC address rule, which is not what is intended.

Did you mean the regex to be `^([0-9a-f]{2}[:]){5}([0-9a-f]{2})$`?

**Comment by andrewbonney** [comment] 2018-02-16 22:27
I believe this is a duplicate of https://github.com/AMWA-TV/nmos-discovery-registration/issues/30

The chassis ID validation will execute against the more permissive rule no matter what, but the MAC formatting is provided as a guideline for how MAC addresses should be formatted if they are the value chosen for use in that field.

**Closed as completed by andrewbonney** 2018-02-16 22:27 UTC
Labels: duplicate
